export const RWANDA_DISTRICTS = [
  'Bugesera',
  'Burera',
  'Gakenke',
  'Gasabo',
  'Gatsibo',
  'Kamonyi',
  'Karongi',
  'Kayonza',
  'Kicukiro',
  'Kirehe',
  'Muhanga',
  'Musanze',
  'Ngoma',
  'Ngororero',
  'Nyabihu',
  'Nyagatare',
  'Nyamagabe',
  'Nyamasheke',
  'Nyanza',
  'Nyarugenge',
  'Nyaruguru',
  'Rubavu',
  'Ruhango',
  'Rulindo',
  'Rusizi',
  'Rutsiro',
  'Rwamagana',
] as const;

export type RwandaDistrict = (typeof RWANDA_DISTRICTS)[number];

/** Representative sectors per district (subset for prototype forms). */
export const RWANDA_SECTORS: Record<RwandaDistrict, string[]> = {
  Bugesera: ['Gashora', 'Juru', 'Kamabuye', 'Mareba', 'Nyamata'],
  Burera: ['Bungwe', 'Butaro', 'Cyanika', 'Gahunga', 'Kinoni'],
  Gakenke: ['Busengo', 'Coko', 'Cyabingo', 'Gakenke', 'Gashenyi'],
  Gasabo: ['Bumbogo', 'Gatsata', 'Jali', 'Kacyiru', 'Remera'],
  Gatsibo: ['Gatsibo', 'Gitoki', 'Kabarore', 'Kageyo', 'Murambi'],
  Kamonyi: ['Kabuga', 'Kamonyi', 'Kayenzi', 'Mugina', 'Runda'],
  Karongi: ['Bwishyura', 'Gishyita', 'Gitesi', 'Mubuga', 'Rugabano'],
  Kayonza: ['Gahini', 'Kabare', 'Kabarondo', 'Mukarange', 'Rwinkwavu'],
  Kicukiro: ['Gahanga', 'Gatenga', 'Kagarama', 'Kicukiro', 'Niboye'],
  Kirehe: ['Gahara', 'Gatore', 'Kigarama', 'Kirehe', 'Mpanga'],
  Muhanga: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Muhanga', 'Shyogwe'],
  Musanze: ['Busogo', 'Gacaca', 'Gashaki', 'Kinigi', 'Muhoza'],
  Ngoma: ['Gashanda', 'Jarama', 'Karembo', 'Mutenderi', 'Rukira'],
  Ngororero: ['Bwira', 'Gatumba', 'Kavumu', 'Matyazo', 'Ngororero'],
  Nyabihu: ['Bigogwe', 'Jenda', 'Jomba', 'Kabatwa', 'Rugera'],
  Nyagatare: ['Gatunda', 'Karangazi', 'Katabagemu', 'Matimba', 'Rwempasha'],
  Nyamagabe: ['Buruhukiro', 'Cyanika', 'Gatare', 'Kaduha', 'Mugano'],
  Nyamasheke: ['Bushekeri', 'Cyato', 'Gihombo', 'Kagano', 'Rangiro'],
  Nyanza: ['Busasamana', 'Cyabakamyi', 'Kibirizi', 'Mukingo', 'Ntyazo'],
  Nyarugenge: ['Gitega', 'Kanyinya', 'Kigali', 'Mageragere', 'Nyakabanda'],
  Nyaruguru: ['Cyahinda', 'Kibeho', 'Kivu', 'Mata', 'Ngera'],
  Rubavu: ['Bugeshi', 'Busasamana', 'Gisenyi', 'Kanama', 'Nyakiriba'],
  Ruhango: ['Bweramana', 'Byimana', 'Kabagali', 'Kinazi', 'Mbuye'],
  Rulindo: ['Base', 'Burega', 'Cyinzuzi', 'Kinihira', 'Ngoma'],
  Rusizi: ['Bugarama', 'Butare', 'Gihundwe', 'Kamembe', 'Muganza'],
  Rutsiro: ['Gihango', 'Kigeyo', 'Mubuga', 'Murunda', 'Rusebeya'],
  Rwamagana: ['Fumbwe', 'Gahengeri', 'Karenge', 'Musha', 'Nyakariro'],
};
